[2025-06-12T19:25:10.543+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prediccion_modelo_produccion_dag.predecir manual__2025-06-01T17:12:25.032844+00:00 [queued]>
[2025-06-12T19:25:10.575+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prediccion_modelo_produccion_dag.predecir manual__2025-06-01T17:12:25.032844+00:00 [queued]>
[2025-06-12T19:25:10.575+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-06-12T19:25:10.624+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): predecir> on 2025-06-01 17:12:25.032844+00:00
[2025-06-12T19:25:10.648+0000] {standard_task_runner.py:60} INFO - Started process 1096 to run task
[2025-06-12T19:25:10.692+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'prediccion_modelo_produccion_dag', 'predecir', 'manual__2025-06-01T17:12:25.032844+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/prediccion_modelo_produccion_dag.py', '--cfg-path', '/tmp/tmpa4pn2e48']
[2025-06-12T19:25:10.697+0000] {standard_task_runner.py:88} INFO - Job 63: Subtask predecir
[2025-06-12T19:25:10.887+0000] {task_command.py:423} INFO - Running <TaskInstance: prediccion_modelo_produccion_dag.predecir manual__2025-06-01T17:12:25.032844+00:00 [running]> on host 24edc8b790cf
[2025-06-12T19:25:11.419+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fede' AIRFLOW_CTX_DAG_ID='prediccion_modelo_produccion_dag' AIRFLOW_CTX_TASK_ID='predecir' AIRFLOW_CTX_EXECUTION_DATE='2025-06-01T17:12:25.032844+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-01T17:12:25.032844+00:00'
[2025-06-12T19:25:15.278+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/mlflow/store/artifact/utils/models.py:31 FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
[2025-06-12T19:25:15.400+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/prediccion_modelo_produccion_dag.py", line 49, in predecir
    model = mlflow.sklearn.load_model(f"models:/{model_name}/{stage}")
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/sklearn/__init__.py", line 633, in load_model
    local_model_path = _download_artifact_from_uri(artifact_uri=model_uri, output_path=dst_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/tracking/artifact_utils.py", line 108, in _download_artifact_from_uri
    repo = get_artifact_repository(artifact_uri=root_uri)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 132, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 77, in get_artifact_repository
    return repository(artifact_uri)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/store/artifact/models_artifact_repo.py", line 69, in __init__
    ) = ModelsArtifactRepository._get_model_uri_infos(artifact_uri)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/store/artifact/models_artifact_repo.py", line 103, in _get_model_uri_infos
    name, version = get_model_name_and_version(client, uri)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/store/artifact/utils/models.py", line 93, in get_model_name_and_version
    return model_name, str(_get_latest_model_version(client, model_name, model_stage))
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/store/artifact/utils/models.py", line 31, in _get_latest_model_version
    latest = client.get_latest_versions(name, None if stage is None else [stage])
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/utils/annotations.py", line 145, in deprecated_func
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/tracking/client.py", line 3487, in get_latest_versions
    return self._get_registry_client().get_latest_versions(name, stages)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/tracking/_model_registry/client.py", line 153, in get_latest_versions
    return self.store.get_latest_versions(name, stages)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/store/model_registry/rest_store.py", line 193, in get_latest_versions
    response_proto = self._call_endpoint(GetLatestVersions, req_body, call_all_endpoints=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/store/model_registry/base_rest_store.py", line 39, in _call_endpoint
    return call_endpoints(
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 387, in call_endpoints
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 382, in call_endpoints
    return call_endpoint(
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 370, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 240, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: RESOURCE_DOES_NOT_EXIST: Registered Model with name=mejor_modelo_orquestado not found
[2025-06-12T19:25:15.447+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=prediccion_modelo_produccion_dag, task_id=predecir, execution_date=20250601T171225, start_date=20250612T192510, end_date=20250612T192515
[2025-06-12T19:25:15.483+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 63 for task predecir (RESOURCE_DOES_NOT_EXIST: Registered Model with name=mejor_modelo_orquestado not found; 1096)
[2025-06-12T19:25:15.570+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-12T19:25:15.637+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
