[2025-06-21T14:40:52.960+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: entrenamiento_modelos_regresion.entrenar_y_promover scheduled__2025-06-19T21:00:00+00:00 [queued]>
[2025-06-21T14:40:52.973+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: entrenamiento_modelos_regresion.entrenar_y_promover scheduled__2025-06-19T21:00:00+00:00 [queued]>
[2025-06-21T14:40:52.973+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-06-21T14:40:52.997+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): entrenar_y_promover> on 2025-06-19 21:00:00+00:00
[2025-06-21T14:40:53.005+0000] {standard_task_runner.py:60} INFO - Started process 207 to run task
[2025-06-21T14:40:53.012+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'entrenamiento_modelos_regresion', 'entrenar_y_promover', 'scheduled__2025-06-19T21:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/entrenamiento_modelos_regresion_dag.py', '--cfg-path', '/tmp/tmpognz1ao1']
[2025-06-21T14:40:53.017+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask entrenar_y_promover
[2025-06-21T14:40:53.133+0000] {task_command.py:423} INFO - Running <TaskInstance: entrenamiento_modelos_regresion.entrenar_y_promover scheduled__2025-06-19T21:00:00+00:00 [running]> on host 1500838101db
[2025-06-21T14:40:53.276+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fede' AIRFLOW_CTX_DAG_ID='entrenamiento_modelos_regresion' AIRFLOW_CTX_TASK_ID='entrenar_y_promover' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-19T21:00:00+00:00'
[2025-06-21T14:40:53.199+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:59 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-06-21T14:40:53.214+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:62 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-06-21T14:40:53.217+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:64 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-06-21T14:40:53.219+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:65 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-06-21T14:40:53.436+0000] {logging_mixin.py:188} WARNING - 2025/06/21 14:40:53 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-06-21T14:40:58.100+0000] {logging_mixin.py:188} WARNING - 2025/06/21 14:40:58 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-21T14:40:58.199+0000] {logging_mixin.py:188} WARNING - 2025/06/21 14:40:58 INFO mlflow.tracking._tracking_service.client: üèÉ View run RandomForest at: http://mlflow:5000/#/experiments/1/runs/53721129dc3a4604b2cf62250927e6e0.
[2025-06-21T14:40:58.200+0000] {logging_mixin.py:188} WARNING - 2025/06/21 14:40:58 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-06-21T14:41:01.381+0000] {logging_mixin.py:188} WARNING - 2025/06/21 14:41:01 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-21T14:41:01.442+0000] {logging_mixin.py:188} WARNING - 2025/06/21 14:41:01 INFO mlflow.tracking._tracking_service.client: üèÉ View run GradientBoosting at: http://mlflow:5000/#/experiments/1/runs/255ed85413164bcf9590577b368c9cd5.
[2025-06-21T14:41:01.442+0000] {logging_mixin.py:188} WARNING - 2025/06/21 14:41:01 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-06-21T14:41:04.322+0000] {logging_mixin.py:188} WARNING - 2025/06/21 14:41:04 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-21T14:41:04.467+0000] {logging_mixin.py:188} WARNING - 2025/06/21 14:41:04 INFO mlflow.tracking._tracking_service.client: üèÉ View run SVR at: http://mlflow:5000/#/experiments/1/runs/ee398d36ea5244f0b88f850564fcc200.
[2025-06-21T14:41:04.468+0000] {logging_mixin.py:188} WARNING - 2025/06/21 14:41:04 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-06-21T14:41:04.538+0000] {logging_mixin.py:188} WARNING - Successfully registered model 'mejor_modelo_orquestado'.
[2025-06-21T14:41:04.634+0000] {logging_mixin.py:188} WARNING - 2025/06/21 14:41:04 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: mejor_modelo_orquestado, version 1
[2025-06-21T14:41:04.635+0000] {logging_mixin.py:188} WARNING - Created version '1' of model 'mejor_modelo_orquestado'.
[2025-06-21T14:41:04.636+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:111 FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
[2025-06-21T14:41:04.656+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:115 FutureWarning: ``mlflow.tracking.client.MlflowClient.transition_model_version_stage`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
[2025-06-21T14:41:04.793+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-21T14:41:04.818+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=entrenamiento_modelos_regresion, task_id=entrenar_y_promover, execution_date=20250619T210000, start_date=20250621T144052, end_date=20250621T144104
[2025-06-21T14:41:04.877+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-21T14:41:04.913+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
