[2025-06-18T01:26:43.320+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: entrenamiento_modelos_regresion.entrenar_y_promover manual__2025-06-18T01:19:35.340643+00:00 [queued]>
[2025-06-18T01:26:43.332+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: entrenamiento_modelos_regresion.entrenar_y_promover manual__2025-06-18T01:19:35.340643+00:00 [queued]>
[2025-06-18T01:26:43.332+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-06-18T01:26:43.349+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): entrenar_y_promover> on 2025-06-18 01:19:35.340643+00:00
[2025-06-18T01:26:43.358+0000] {standard_task_runner.py:60} INFO - Started process 202 to run task
[2025-06-18T01:26:43.365+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'entrenamiento_modelos_regresion', 'entrenar_y_promover', 'manual__2025-06-18T01:19:35.340643+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/entrenamiento_modelos_regresion_dag.py', '--cfg-path', '/tmp/tmpxli3ir5v']
[2025-06-18T01:26:43.370+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask entrenar_y_promover
[2025-06-18T01:26:43.471+0000] {task_command.py:423} INFO - Running <TaskInstance: entrenamiento_modelos_regresion.entrenar_y_promover manual__2025-06-18T01:19:35.340643+00:00 [running]> on host b043483ba5b8
[2025-06-18T01:26:43.659+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fede' AIRFLOW_CTX_DAG_ID='entrenamiento_modelos_regresion' AIRFLOW_CTX_TASK_ID='entrenar_y_promover' AIRFLOW_CTX_EXECUTION_DATE='2025-06-18T01:19:35.340643+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-18T01:19:35.340643+00:00'
[2025-06-18T01:26:47.921+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:59 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-06-18T01:26:47.938+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:62 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-06-18T01:26:47.941+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:64 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-06-18T01:26:47.943+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:65 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-06-18T01:26:48.715+0000] {logging_mixin.py:188} WARNING - 2025/06/18 01:26:48 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-06-18T01:26:53.540+0000] {logging_mixin.py:188} WARNING - 2025/06/18 01:26:53 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-18T01:26:53.736+0000] {logging_mixin.py:188} WARNING - 2025/06/18 01:26:53 INFO mlflow.tracking._tracking_service.client: üèÉ View run RandomForest at: http://mlflow:5000/#/experiments/1/runs/ab3d705970244cf19aef0fa2bbca3bb5.
[2025-06-18T01:26:53.736+0000] {logging_mixin.py:188} WARNING - 2025/06/18 01:26:53 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-06-18T01:26:58.265+0000] {logging_mixin.py:188} WARNING - 2025/06/18 01:26:58 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-18T01:26:58.507+0000] {logging_mixin.py:188} WARNING - 2025/06/18 01:26:58 INFO mlflow.tracking._tracking_service.client: üèÉ View run GradientBoosting at: http://mlflow:5000/#/experiments/1/runs/8fdd1d40685348c2bcf7dcb8406c7356.
[2025-06-18T01:26:58.507+0000] {logging_mixin.py:188} WARNING - 2025/06/18 01:26:58 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-06-18T01:27:01.223+0000] {logging_mixin.py:188} WARNING - 2025/06/18 01:27:01 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-18T01:27:01.420+0000] {logging_mixin.py:188} WARNING - 2025/06/18 01:27:01 INFO mlflow.tracking._tracking_service.client: üèÉ View run SVR at: http://mlflow:5000/#/experiments/1/runs/b05ef77b33384558808d4dd89790af59.
[2025-06-18T01:27:01.421+0000] {logging_mixin.py:188} WARNING - 2025/06/18 01:27:01 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-06-18T01:27:02.130+0000] {logging_mixin.py:188} WARNING - Successfully registered model 'mejor_modelo_orquestado'.
[2025-06-18T01:27:02.236+0000] {logging_mixin.py:188} WARNING - 2025/06/18 01:27:02 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: mejor_modelo_orquestado, version 1
[2025-06-18T01:27:02.236+0000] {logging_mixin.py:188} WARNING - Created version '1' of model 'mejor_modelo_orquestado'.
[2025-06-18T01:27:02.239+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:111 FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
[2025-06-18T01:27:02.350+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:115 FutureWarning: ``mlflow.tracking.client.MlflowClient.transition_model_version_stage`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
[2025-06-18T01:27:02.437+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-18T01:27:02.455+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=entrenamiento_modelos_regresion, task_id=entrenar_y_promover, execution_date=20250618T011935, start_date=20250618T012643, end_date=20250618T012702
[2025-06-18T01:27:02.524+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-18T01:27:02.560+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
