[2025-06-01T00:02:45.896+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prediccion_modelo_produccion_dag.predecir scheduled__2025-05-30T22:00:00+00:00 [queued]>
[2025-06-01T00:02:45.904+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prediccion_modelo_produccion_dag.predecir scheduled__2025-05-30T22:00:00+00:00 [queued]>
[2025-06-01T00:02:45.905+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-06-01T00:02:45.921+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): predecir> on 2025-05-30 22:00:00+00:00
[2025-06-01T00:02:45.928+0000] {standard_task_runner.py:60} INFO - Started process 325 to run task
[2025-06-01T00:02:45.933+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'prediccion_modelo_produccion_dag', 'predecir', 'scheduled__2025-05-30T22:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/prediccion_modelo_produccion_dag.py', '--cfg-path', '/tmp/tmp99n92bah']
[2025-06-01T00:02:45.935+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask predecir
[2025-06-01T00:02:46.024+0000] {task_command.py:423} INFO - Running <TaskInstance: prediccion_modelo_produccion_dag.predecir scheduled__2025-05-30T22:00:00+00:00 [running]> on host 7da8d73ce59f
[2025-06-01T00:02:46.156+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fede' AIRFLOW_CTX_DAG_ID='prediccion_modelo_produccion_dag' AIRFLOW_CTX_TASK_ID='predecir' AIRFLOW_CTX_EXECUTION_DATE='2025-05-30T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-30T22:00:00+00:00'
[2025-06-01T00:02:47.488+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/mlflow/store/artifact/utils/models.py:31 FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
[2025-06-01T00:02:48.399+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/prediccion_modelo_produccion_dag.py", line 46, in predecir
    predicciones = model.predict(nuevos_datos)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py", line 984, in predict
    X = self._validate_X_predict(X)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py", line 599, in _validate_X_predict
    X = self._validate_data(X, dtype=DTYPE, accept_sparse="csr", reset=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/base.py", line 580, in _validate_data
    self._check_feature_names(X, reset=reset)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/base.py", line 507, in _check_feature_names
    raise ValueError(message)
ValueError: The feature names should match those that were passed during fit.
Feature names must be in the same order as they were in fit.

[2025-06-01T00:02:48.420+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=prediccion_modelo_produccion_dag, task_id=predecir, execution_date=20250530T220000, start_date=20250601T000245, end_date=20250601T000248
[2025-06-01T00:02:48.440+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 10 for task predecir (The feature names should match those that were passed during fit.
Feature names must be in the same order as they were in fit.
; 325)
[2025-06-01T00:02:48.492+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-01T00:02:48.539+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
